### ISSUE TITLE
Dataset request: <dataset title>

### ISSUE THREAD

**Issue by natgeo-wong** [datagovsg/datagovsg-datasets#126]
### Please provide the name of the dataset or describe the dataset that you're requesting:
Real-time meteorological datasets for:
- rainfall
- air temperature
- relative humidity
- wind speed
- wind direction

### Do you know which agency provides/can provide this data?
*( Refer to this link for a full list of agencies: https://data.gov.sg/organization )*
National Environmental Agency

### If there's an issue with a dataset, please provide a description of the problem
The data provided is no longer real-time, and previously available data has been redacted.

### Please provide the fields expected in this dataset:
*(e.g. month | country | passengers)*

for eg.
station | value | time
------|---------|-------------
S24 | 0.2 | 2017-12-32T23:55:00 (rainfall)

### How frequently would you need this dataset to be updated?
Example: 
- [X] *Test*

- [ ] Annually
- [ ] Monthly
- [ ] Weekly
- [ ] Daily
- [ ] Hourly
- [X] Real-time

### Can you give a short explanation on how you're planning to use this dataset?
Using for data analysis of Singapore's meteorological data to analyse trends.

**Comment by lucasarea** [comment]
I found the same problem, the data and the way is provided is really inconsistent. I hope this is solved soon

**Comment by iewil** [comment]
Hi @lucasarea and @natwongsedai the only thing we've changed is to remove the requirement of having an API key. The response from our APIs should remain the same. Would you be able to help provide examples of what has changed so that we can troubleshoot it from our end? Thanks!

**Comment by lucasarea** [comment]
I have been requesting every 5 minutes and saving the data retrieved since last week of Air Temperature, Relative Humidity and Rainfall.

Quickly looking the files I can see:
- Air Temperature Files:
Number of station's reading differs a lot: while some files I only retrieved data for **2 stations**, other times I retrieve data for **12 stations**
Interval retrieval: I check the timestamp retrieved on the data and it is generally not updated every 5 minutes.

- Rainfall files:
Same issues, but the number of stations on the data is much more stable (most entries seems to have 53 stations)


- Relative Humidity:
Same issues as Air Temperature

I think the attachment helps to understand
Look at the timestamps at the filenames.

![print screen](https://user-images.githubusercontent.com/26867986/37203876-1a92678c-23ca-11e8-9e51-bfc7fb8b5fbc.png)

**Comment by natwongsedai** [comment]
I am not sure if MSS has redacted the data, but when I download data using both API and non-API, I only get results for certain stations at certain dates.

Previously, I used to be able to get the whole dataset (in steps of 1 min) for the month, whenever the data was available.  Now, I can only get data from once or twice a day.
