### ISSUE TITLE
Extracting hourly historical weather information

### ISSUE THREAD

**Issue by jasonleebp** [datagovsg/datagovsg-datasets#548]
### Please provide the name of the dataset or describe the dataset that you're requesting:
NEA publishes weather data such as rainfall, temperature and windspeed for the various locations according to the probe. 

### Do you know which agency provides/can provide this data?
NEA

### If there's an issue with a dataset, please provide a description of the problem
Currently, for historical data sets, NEA only make available daily data. For e.g. http://www.weather.gov.sg/climate-historical-daily/ 

### Please provide the fields expected in this dataset:
Would like a finer set of data to the hour for analysis. 
Station | Year | Month | Day | Hour | Rainfall Total (mm) | Mean Temperature (°C) | Maximum Temperature (°C) | Minimum Temperature (°C) | Mean Wind Speed (km/h) | Max Wind Speed (km/h)

### How frequently would you need this dataset to be updated?
Dataset can be updated daily but with details up to the hour. 

### Can you give a short explanation on how you're planning to use this dataset?
Would like to establish if there is any relationship between rainfall and/or temperature on the performance of traffic equipment.

**Comment by maxng07** [comment]
Hi Jason,

I just come across this as I was browsing the issue lists. I'm already using the data you asked for to extend my app for correlation, mainly for avid sports user.
These data measure in Rain Gauge for Rainfall and Wind Speed are updated every 5 mins interval. You can average it out and churn out the mean readings? I'm correlating Rainfall with 2-hour weather forecast based on longitude/latitude using Haversine formulae so user can make informed decision.

Have a look here, note the data is currently unavailable since New Year Eve, but historical data are available.
https://api.data.gov.sg/v1/environment/rainfall
https://api.data.gov.sg/v1/environment/air-temperature

More details here
https://data.gov.sg/dataset/realtime-weather-readings

/Max
PS: I'm a fellow consumer of these datasets and provide apps for relevant interest group. I do not work for GovTech.
